from __future__ import annotations

from typing import Protocol, runtime_checkable


PowerCommandResult = tuple[bool, str]


@runtime_checkable
class PowerControllerProtocol(Protocol):
    power_source_key: str
    power_source_name: str
    supports_internal_current_readback: bool
    is_connected: bool

    def set_voltage(self, voltage: float) -> PowerCommandResult: ...
    def set_voltage_only(self, voltage: float) -> PowerCommandResult: ...
    def read_voltage(self): ...
    def read_current(self): ...
    def enable_high_voltage(self) -> PowerCommandResult: ...
    def disable_high_voltage(self) -> PowerCommandResult: ...
    def stop_output(self) -> PowerCommandResult: ...
    def reset_voltage(self) -> PowerCommandResult: ...


@runtime_checkable
class ActualVoltageReadableControllerProtocol(PowerControllerProtocol, Protocol):
    def read_actual_voltage(self): ...


@runtime_checkable
class SerialRemotePowerControllerProtocol(ActualVoltageReadableControllerProtocol, Protocol):
    def connect_serial(self, port, baudrate: int = 9600): ...
    def enable_remote_control(self, timeout_s: float = 2.0) -> PowerCommandResult: ...
    def disconnect(self): ...
